# NumPy :

It stands for Numerical Python.

Why do we use NumPy over normal list ?

1. Faster operations.

2. It provides several mathematical operations.



In [1]:
#importing numpy library:
import numpy as np

Time taken by numpy vs lists:

In [3]:
from time import process_time

In [7]:
#time taken by list:
python_list = [i for i in range (10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0013481460000006606


In [15]:
#time taken by numpy array:
np_array = np.array([i for i in range (10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.00013764000000016097


In [17]:
#list:
list = [1,2,34,45]
type(list)

list

In [19]:
np_array = np.array([1,2,34,45])
type(np_array)

numpy.ndarray

In [22]:
#creating a 1-D array:
a = np.array([1,2,3,4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [23]:
#creating a 2-D array:
a = np.array(([1,2,3,4,5],[2,3,4,5,6]))
print(a)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [33]:
b = np.ones((1,2,3))
print(b)
b.ndim

[[[1. 1. 1.]
  [1. 1. 1.]]]


3

In [35]:
#initial placeholders in numpy array:
#creating an array of zeros of given shape:
x = np.zeros((4,5,6))
print(x)
print(type(x))
x.ndim

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
<class 'numpy.ndarray'>


3

In [38]:
x = np.ones((10,9))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [40]:
#creating an identity matrix:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
#creating a numpy array of particular value:
a = np.full((4,6),8)
print(a)

[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]


In [44]:
#creating a numpy array of random numbers:
a = np.random.random((4,5))
print(a)

[[0.56137777 0.17999507 0.93869462 0.34175343 0.80984887]
 [0.92236027 0.32196732 0.07731974 0.44041346 0.07110537]
 [0.54823491 0.04599264 0.60016749 0.53357382 0.49206997]
 [0.60577865 0.00552333 0.46841997 0.75909788 0.09389288]]


In [45]:
#creating a numpy array of some random integers:
c = np.random.randint(10,50,(4,5))
print(c)

[[25 27 22 44 34]
 [18 12 11 34 44]
 [48 41 34 48 11]
 [42 17 14 17 42]]


In [48]:
#array of evenly spaced values:
a = np.linspace(15, 10, 4)
print(a) 

[15.         13.33333333 11.66666667 10.        ]


In [52]:
#creating an array of numbers at a particular step:
a = np.arange(10,20,1)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [53]:
p = np.arange(10,30,6)
print(p)

[10 16 22 28]


In [55]:
#converting a list into an numpy array:
list2 = [1,2,3,4,5,6,7]
array = np.asarray(list2)
print(array)

[1 2 3 4 5 6 7]


In [56]:
type(array)

numpy.ndarray

In [58]:
#analysing a numpy array:
s = np.random.randint(19,35,(5,6))
print(s)

[[27 24 20 32 29 30]
 [34 22 29 26 31 28]
 [29 33 28 28 28 31]
 [23 25 26 24 23 34]
 [20 31 27 19 27 25]]


In [59]:
#checking the shape of a:
s.shape
print(s.shape)

(5, 6)


In [60]:
#checking the number of dimensions in a given array:
print(s.ndim)

2


In [62]:
print(s.dtype)

int64


*Mathematical Opeartions in NumPy array:*

In [65]:
a = np.random.randint(15,25,(5,5))
b = np.random.randint(29,33,(5,5))
print(a)
print(b)

[[19 21 16 15 22]
 [17 16 23 17 19]
 [16 16 17 16 16]
 [22 15 24 17 20]
 [20 17 23 19 22]]
[[29 32 30 31 32]
 [29 31 32 32 30]
 [30 31 29 29 29]
 [29 29 32 32 30]
 [31 29 32 30 32]]


In [66]:
print(a+b)

[[48 53 46 46 54]
 [46 47 55 49 49]
 [46 47 46 45 45]
 [51 44 56 49 50]
 [51 46 55 49 54]]


In [67]:
print(a-b)

[[-10 -11 -14 -16 -10]
 [-12 -15  -9 -15 -11]
 [-14 -15 -12 -13 -13]
 [ -7 -14  -8 -15 -10]
 [-11 -12  -9 -11 -10]]


In [68]:
print(a*b)

[[551 672 480 465 704]
 [493 496 736 544 570]
 [480 496 493 464 464]
 [638 435 768 544 600]
 [620 493 736 570 704]]


In [69]:
print(a/b)

[[0.65517241 0.65625    0.53333333 0.48387097 0.6875    ]
 [0.5862069  0.51612903 0.71875    0.53125    0.63333333]
 [0.53333333 0.51612903 0.5862069  0.55172414 0.55172414]
 [0.75862069 0.51724138 0.75       0.53125    0.66666667]
 [0.64516129 0.5862069  0.71875    0.63333333 0.6875    ]]


In [78]:
c = np.random.randint(5,6,(4,6))
d = np.random.randint(10,15,(4,6))
print(c)
print(d)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]
[[14 13 11 14 12 12]
 [13 12 13 10 11 13]
 [14 10 12 11 13 14]
 [14 13 12 13 14 12]]


In [79]:
print(np.add(c,d))

[[19 18 16 19 17 17]
 [18 17 18 15 16 18]
 [19 15 17 16 18 19]
 [19 18 17 18 19 17]]


In [80]:
print(np.subtract(c,d))

[[-9 -8 -6 -9 -7 -7]
 [-8 -7 -8 -5 -6 -8]
 [-9 -5 -7 -6 -8 -9]
 [-9 -8 -7 -8 -9 -7]]


In [81]:
print(np.multiply(c,d))

[[70 65 55 70 60 60]
 [65 60 65 50 55 65]
 [70 50 60 55 65 70]
 [70 65 60 65 70 60]]


In [82]:
print(np.divide(c,d))

[[0.35714286 0.38461538 0.45454545 0.35714286 0.41666667 0.41666667]
 [0.38461538 0.41666667 0.38461538 0.5        0.45454545 0.38461538]
 [0.35714286 0.5        0.41666667 0.45454545 0.38461538 0.35714286]
 [0.35714286 0.38461538 0.41666667 0.38461538 0.35714286 0.41666667]]


In [84]:
array = np.random.randint(12,28,(4,6))
print(array)
array.shape

[[23 25 23 27 16 19]
 [13 12 17 18 19 12]
 [21 24 27 21 12 23]
 [27 27 12 18 27 22]]


(4, 6)

In [85]:
trans = np.transpose(array)
print(trans)
trans.shape

[[23 13 21 27]
 [25 12 24 27]
 [23 17 27 12]
 [27 18 21 18]
 [16 19 12 27]
 [19 12 23 22]]


(6, 4)

In [91]:
array1 = np.random.randint(25,30,(6,7))
print(array1)

[[26 26 28 29 29 29 28]
 [29 29 25 25 29 25 25]
 [29 26 29 26 28 27 29]
 [27 28 27 25 26 26 27]
 [29 26 26 27 25 29 25]
 [25 26 27 25 26 26 27]]


In [92]:
array2 = array1.reshape(7,6)
print(array2)

[[26 26 28 29 29 29]
 [28 29 29 25 25 29]
 [25 25 29 26 29 26]
 [28 27 29 27 28 27]
 [25 26 26 27 29 26]
 [26 27 25 29 25 25]
 [26 27 25 26 26 27]]
